import { useEffect, useState } from 'react';
import { supabase } from '../../lib/supabase';
import gamingMascot from '../../../docs/assets/mascot/mascot_gaming.png';
import eventMascot from '../../../docs/assets/mascot/mascot_sunglasses.png';
import snuBanner from '../../../docs/assets/snu_partnership_banner.png';

type Item={id:string;title:string;players?:string|null;genre?:string|null;content?:string|null;is_always_on?:boolean};

export function PublicInfoPage({kind}:{kind:'games'|'events'|'store'}){
  const [items,setItems]=useState<Item[]|null>(null); const [storeText,setStoreText]=useState(''); const [error,setError]=useState(false);
  const copy=kind==='games'?['GAME LIBRARY','게임 목록','현재 공개된 게임이 없습니다. 확인된 목록만 안내합니다.']:kind==='events'?['EVENTS & NOTICE','이벤트·공지','진행 중인 이벤트가 없습니다.']:['STORE GUIDE','매장 안내','매장 정보가 준비 중입니다.'];
  useEffect(()=>{if(!supabase){setItems([]);return}const today=new Date().toISOString().slice(0,10);const query=kind==='store'?supabase.from('store_content').select('content_value').eq('content_key','store').maybeSingle():kind==='games'?supabase.from('entertainment_items').select('id,title,players,genre').eq('is_verified',true).eq('is_available',true).is('archived_at',null):supabase.from('store_events').select('id,title,content,is_always_on').eq('is_public',true).is('archived_at',null).or('is_always_on.eq.true,and(start_date.lte.'+today+',end_date.gte.'+today+')');void query.then(({data,error})=>{if(error){setError(true);return}if(kind==='store')setStoreText((data as {content_value?:{text?:string}}|null)?.content_value?.text??'');else setItems((data??[]) as Item[])});},[kind]);
  if(kind==='store')return <main className="content-page"><p className="section-kicker">{copy[0]}</p><h1>{copy[1]}</h1><p className="page-lede">{error?'정보를 불러오지 못했습니다.':storeText||copy[2]}</p><a className="primary-action" href="/">홈으로 돌아가기 <span>→</span></a></main>;
  return <main className="content-page"><style>{'.public-hero{display:flex;align-items:center;justify-content:space-between;gap:20px;padding:24px;background:#1e1e1e;border:3px solid #1e1e1e;border-radius:23px;color:#fff9ec}.public-hero img{width:96px;height:96px;object-fit:contain}.game-list,.event-list{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:13px;margin-top:22px}.game-list article,.event-list article{padding:17px;border:2.5px solid #1e1e1e;border-radius:18px;background:#fff}.game-list b,.event-list b{display:inline-block;padding:4px 8px;border-radius:7px;background:#1e1e1e;color:#fed943;font-size:10px}.game-list h2,.event-list h2{font-size:17px;margin:13px 0 7px}.game-list p,.event-list p{margin:0;color:#6b6354;font-size:13px;line-height:1.55}.event-list article:first-child{grid-column:span 2;background:#fff9ec}.event-list img{max-width:100%;max-height:130px;object-fit:contain;margin-top:14px}@media(max-width:720px){.game-list,.event-list{grid-template-columns:1fr}.event-list article:first-child{grid-column:auto}}'}</style><section className="public-hero"><div><p className="section-kicker" style={{color:'#fed943'}}>{copy[0]}</p><h1>{copy[1]}</h1><p>{kind==='games'?'매장에서 확인한 게임만 안내합니다.':'진행 중인 제휴 혜택과 이벤트를 확인하세요.'}</p></div><img src={kind==='games'?gamingMascot:eventMascot} alt=""/></section>{error?<p className="state-card">정보를 불러오지 못했습니다. 잠시 후 다시 시도해 주세요.</p>:items===null?<p className="state-card">정보를 불러오는 중입니다.</p>:items.length===0?<p className="state-card">{copy[2]}</p>:<section className={kind==='games'?'game-list':'event-list'}>{items.map((item,index)=><article key={item.id}><b>{kind==='games'?'VERIFIED':item.is_always_on?'ONGOING':'EVENT'}</b><h2>{item.title}</h2><p>{kind==='games'?[item.players,item.genre].filter(Boolean).join(' · ')||'인원·장르 정보 확인 중':item.content}</p>{kind==='events'&&index===0&&<img src={snuBanner} alt="서울대학교 제휴 안내"/>}</article>)}</section>}</main>;
}
