import { FormEvent, useEffect, useRef, useState } from 'react';
import { speakKorean } from '../../lib/broadcast';
import { isDue, type ScheduledBroadcast } from '../../lib/broadcastSchedule';
import { supabase } from '../../lib/supabase';

const presets = [['기본', '/audio/기본.mp3'], ['마감', '/audio/마감.mp3'], ['만석', '/audio/만석.mp3'], ['소음', '/audio/소음.mp3'], ['신분증 검사', '/audio/신분증검사.mp3'], ['음료 픽업 요청', '/audio/음료픽업요청.mp3']] as const;
type StoredSchedule = ScheduledBroadcast & { id: string; message_text: string };
type FailedRun = { id: string; message_text: string; triggered_at: string };
type ScheduleForm = { message: string; type: ScheduledBroadcast['scheduleType']; time: string; date: string; weekdays: string[] };
const emptySchedule: ScheduleForm = { message: '', type: 'daily', time: '09:00', date: '', weekdays: ['MON', 'TUE', 'WED', 'THU', 'FRI'] };

export function BroadcastPage() {
  const [text, setText] = useState(''); const [status, setStatus] = useState('대기'); const [schedules, setSchedules] = useState<StoredSchedule[]>([]); const [schedule, setSchedule] = useState<ScheduleForm>(emptySchedule); const [scheduleStatus, setScheduleStatus] = useState(''); const [failedRuns, setFailedRuns] = useState<FailedRun[]>([]); const executedKeys = useRef(new Set<string>());
  const recordRun = async (message: string, scheduledId?: string) => { if (!supabase) return; const { data } = await supabase.from('broadcast_runs').insert({ scheduled_broadcast_id: scheduledId ?? null, message_text: message, status: 'pending' }).select('id').single(); return data?.id as string | undefined; };
  const finishRun = async (id: string | undefined, success: boolean) => { if (id && supabase) await supabase.from('broadcast_runs').update(success ? { status: 'success' } : { status: 'failure', error_message: '브라우저 음성 재생 실패' }).eq('id', id); };
  const loadFailedRuns = async () => { if (!supabase) return; const { data } = await supabase.from('broadcast_runs').select('id, message_text, triggered_at').eq('status', 'failure').order('triggered_at', { ascending: false }).limit(10); setFailedRuns((data ?? []) as FailedRun[]); };
  const play = async (value: string, scheduledId?: string) => { setStatus('재생 중'); const runId = await recordRun(value, scheduledId); try { await speakKorean(value); await finishRun(runId, true); setStatus('성공'); await loadFailedRuns(); } catch { await finishRun(runId, false); setStatus('실패'); await loadFailedRuns(); } };
  const playAudio = async (src: string, title: string) => { setStatus('재생 중'); const runId = await recordRun(title); try { const audio = new Audio(`${import.meta.env.BASE_URL}${src.replace(/^\//, '')}`); await audio.play(); audio.onended = () => { void finishRun(runId, true); setStatus('성공'); }; audio.onerror = () => { void finishRun(runId, false); void loadFailedRuns(); setStatus('실패'); }; } catch { await finishRun(runId, false); await loadFailedRuns(); setStatus('실패'); } };
  const loadSchedules = async () => { if (!supabase) return; const { data, error } = await supabase.from('scheduled_broadcasts').select('id, message_text, schedule_type, target_time, target_days, target_date, is_enabled').is('archived_at', null).order('target_time'); if (error) { setScheduleStatus(`예약을 불러오지 못했습니다: ${error.message}`); return; } setSchedules((data ?? []).map((item) => ({ id: item.id, message_text: item.message_text, scheduleType: item.schedule_type, targetTime: item.target_time.slice(0, 5), targetDays: item.target_days ?? [], targetDate: item.target_date ?? undefined, isEnabled: item.is_enabled })) as StoredSchedule[]); };
  useEffect(() => { void loadSchedules(); void loadFailedRuns(); }, []);
  useEffect(() => { const runDueSchedules = async () => { const now = new Date(); for (const item of schedules) { const key = `${item.id}:${now.toISOString().slice(0, 16)}`; if (!isDue(item, now) || executedKeys.current.has(key)) continue; executedKeys.current.add(key); await play(item.message_text, item.id); } }; void runDueSchedules(); const timer = window.setInterval(() => void runDueSchedules(), 15_000); return () => window.clearInterval(timer); }, [schedules]);
  const saveSchedule = async (event: FormEvent) => { event.preventDefault(); if (!supabase) { setScheduleStatus('Supabase 연결 설정이 필요합니다.'); return; } setScheduleStatus('저장 중'); const { data: store, error: storeError } = await supabase.from('stores').select('id').eq('slug', 'snu').single(); if (storeError || !store) { setScheduleStatus('서울대입구역점 정보를 찾을 수 없습니다.'); return; } const { error } = await supabase.from('scheduled_broadcasts').insert({ store_id: store.id, message_text: schedule.message.trim(), schedule_type: schedule.type, target_time: schedule.time, target_days: schedule.type === 'weekdays' ? schedule.weekdays : null, target_date: schedule.type === 'once' ? schedule.date : null, is_enabled: true }); if (error) { setScheduleStatus(`저장하지 못했습니다: ${error.message}`); return; } setSchedule(emptySchedule); setScheduleStatus('예약 방송을 저장했습니다.'); await loadSchedules(); };
  const toggleSchedule = async (item: StoredSchedule) => { if (!supabase) return; const { error } = await supabase.from('scheduled_broadcasts').update({ is_enabled: !item.isEnabled }).eq('id', item.id); if (error) { setScheduleStatus(`변경하지 못했습니다: ${error.message}`); return; } await loadSchedules(); };
  return <main className="app-notice"><h1>매장 방송</h1><p>PC 브라우저를 열어 두면 저장된 예약 문구를 해당 시각에 자동으로 방송합니다.</p><section><h2>자주 쓰는 녹음 방송</h2>{presets.map(([title, src]) => <button key={src} onClick={() => void playAudio(src, title)}>{title}</button>)}</section><section><h2>직접 방송</h2><textarea value={text} onChange={(event) => setText(event.target.value)} placeholder="직접 입력 방송" /><button onClick={() => void play(text)} disabled={!text.trim()}>직접 방송</button></section><section><h2>예약 방송 추가</h2><form onSubmit={(event) => void saveSchedule(event)}><textarea required value={schedule.message} onChange={(event) => setSchedule({ ...schedule, message: event.target.value })} placeholder="자동으로 읽을 방송 문구" /><select value={schedule.type} onChange={(event) => setSchedule({ ...schedule, type: event.target.value as typeof schedule.type })}><option value="daily">매일 반복</option><option value="weekdays">요일 반복</option><option value="once">일회성</option></select><input required type="time" value={schedule.time} onChange={(event) => setSchedule({ ...schedule, time: event.target.value })} />{schedule.type === 'weekdays' && <fieldset><legend>반복 요일</legend>{['MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN'].map((day) => <label key={day}><input type="checkbox" checked={schedule.weekdays.includes(day)} onChange={() => setSchedule({ ...schedule, weekdays: schedule.weekdays.includes(day) ? schedule.weekdays.filter((value) => value !== day) : [...schedule.weekdays, day] })} />{day}</label>)}</fieldset>}{schedule.type === 'once' && <input required type="date" value={schedule.date} onChange={(event) => setSchedule({ ...schedule, date: event.target.value })} />}<button type="submit">예약 저장</button></form>{scheduleStatus && <p>{scheduleStatus}</p>}<h2>저장된 예약</h2>{schedules.length === 0 ? <p>저장된 예약이 없습니다.</p> : <ul>{schedules.map((item) => <li key={item.id}><strong>{item.targetTime}</strong> · {item.message_text} · {item.scheduleType} <button onClick={() => void toggleSchedule(item)}>{item.isEnabled ? '끄기' : '켜기'}</button></li>)}</ul>}<h2>실패한 방송</h2>{failedRuns.length === 0 ? <p>실패 기록이 없습니다.</p> : <ul>{failedRuns.map((run) => <li key={run.id}>{run.message_text} <button onClick={() => void play(run.message_text)}>다시 재생</button></li>)}</ul>}</section><p>상태: {status}</p></main>;
}
