import { useEffect, useState } from 'react';
import { validateInventoryCsv } from '../../lib/inventoryImport';
import { parseBaselineInventory } from '../../lib/inventoryCsv';
import { supabase } from '../../lib/supabase';

export function InventoryPage() {
  const [message, setMessage] = useState('');
  const [items, setItems] = useState<Array<{ id: string; volume_range: string; shelf_location: string; archived_at: string | null; books: { title: string; author: string; category: string }[] }>>([]);
  const load = async () => { if (!supabase) return; const { data, error } = await supabase.from('book_inventories').select('id,volume_range,shelf_location,archived_at,books(title,author,category)').order('updated_at', { ascending: false }); if (error) setMessage(error.message); else setItems(data ?? []); };
  useEffect(() => { void load(); }, []);
  const save = async (form: FormData) => { const { error } = await supabase!.rpc('upsert_inventory', { p_title: String(form.get('title')), p_author: String(form.get('author')), p_category: String(form.get('category')), p_volume_range: String(form.get('volume')), p_shelf_location: String(form.get('shelf')) }); setMessage(error?.message ?? '재고를 저장했습니다.'); if (!error) await load(); };
  const importCsv = async (file: File) => { const text = await file.text(); const validation = validateInventoryCsv(text); if (validation) return setMessage(validation); let done = 0; for (const book of parseBaselineInventory(text)) { const { error } = await supabase!.rpc('upsert_inventory', { p_title: book.title, p_author: book.author, p_category: book.category, p_volume_range: book.volumeRange || '확인 중', p_shelf_location: book.shelfLocation }); if (error) return setMessage(error.message); done += 1; } setMessage(`${done}개 재고를 추가하거나 갱신했습니다. 기존에만 있던 재고는 유지됩니다.`); };
  const archive = async (id: string, archived: boolean) => { const { error } = await supabase!.rpc('set_inventory_archive', { p_inventory_id: id, p_archived: archived }); setMessage(error?.message ?? (archived ? '재고를 보관했습니다.' : '재고를 복구했습니다.')); if (!error) await load(); };
  return <main className="app-notice"><h1>도서 재고 관리</h1><form onSubmit={(e) => { e.preventDefault(); void save(new FormData(e.currentTarget)); }}><input name="title" placeholder="도서명" required /><input name="author" placeholder="작가" /><input name="category" placeholder="장르" /><input name="volume" placeholder="보유 권수" required /><input name="shelf" placeholder="서가 위치" required /><button>저장</button></form><label>CSV 가져오기 <input type="file" accept=".csv,text/csv" onChange={(e) => { const file = e.target.files?.[0]; if (file) void importCsv(file); }} /></label><p>{message}</p><h2>등록 재고</h2>{items.map((item) => <section key={item.id}><strong>{item.books[0]?.title}</strong> · {item.books[0]?.author || '작가 미상'} · {item.volume_range} · {item.shelf_location} · {item.archived_at ? '보관됨' : '공개 중'}<button onClick={() => void archive(item.id, !item.archived_at)}>{item.archived_at ? '복구' : '보관'}</button></section>)}</main>;
}
